### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by HorrifyingMonkey** [MY5TERIO/mysterios-playground-modded#3]
HorrifyingMonkey / HorrifyingMonkey#7766

Add a few mods like:

- Mekanism
- Tinkers construct
- thermal expansion

I mean come on, you have extreme reactors and RF xDDD

https://www.curseforge.com/minecraft/mc-mods/tinkers-construct
https://www.curseforge.com/minecraft/mc-mods/mekanism
https://www.curseforge.com/minecraft/mc-mods/thermal-expansion

Also, add the other Luacraft addons like Iron man and ant man

https://www.curseforge.com/minecraft/mc-mods/ironman
https://www.curseforge.com/minecraft/mc-mods/antman
https://www.curseforge.com/minecraft/customization/notenoughheroes

**Comment by MY5TERIO** [comment]
Suggestion is under vote.
